### ISSUE TITLE
About kitti problem

### ISSUE THREAD

**Issue by xuwuzhou** [HKUST-Aerial-Robotics/VINS-Fusion#119]
First , the result of " rosrun vins kitti_odom_test ~/catkin_ws/src/VINS-Fusion/config/kitti_odom/kitti_config00-02.yaml YOUR_DATASET_FOLDER/sequences/00/    "is very good!
![图片](https://user-images.githubusercontent.com/44218507/86575278-96498400-bfa9-11ea-8166-636ed6442080.png)

But when I convert the sequence into rosbag form，and  rosrun vins vins_node ~/catkin_ws/src/VINS-Fusion/config/kitti_odom/kitti_config00-02.yaml , the result is bad，especially the scale（the scale of ground truth is about 100m,but the scale of this is about 100000m）
![图片](https://user-images.githubusercontent.com/44218507/86575262-8fbb0c80-bfa9-11ea-95f6-904b43a534cf.png)

what happened to that?
I can't deal with it.Please help!

**Comment by Astrophil-github** [comment]
Hello, I have also encountered the same problem. Have you resolved it
