### ISSUE TITLE
How to fix features as constant and do motion-only BA

### ISSUE THREAD

**Issue by You-zeyi** [HKUST-Aerial-Robotics/VINS-Fusion#139]
The motion only BA is mentioned in vins-mono paper but I cant see it in the code(vins-mono and vins-fusion). The para_feature was not added to parameterBlock like all other parameters, at least not explicitly, which is puzzling to me. Can I apply SetParameterBlockConstant to para_feature? Should I apply AddParameterBlock first to para_feature before SetParameterBlockConstant.
I would appreciate it if An example code can be provided.

**Comment by aphasiayc** [comment]
> The motion only BA is mentioned in vins-mono

I'm also confused about this para_feature issue... So any update on this thread?  Thanks!

**Comment by YoungsooH** [comment]
Did you find the motion only BA part? I can't find that part too...
