### ISSUE TITLE
MYNTEYE-D have large delay in stereo+imu mode

### ISSUE THREAD

**Issue by shmm91** [HKUST-Aerial-Robotics/VINS-Fusion#16]
Thank you for your great work.
My device is MYNTEYE-D, the image size is 1280*720. When I move the device, the track image and odometry in RVIZ have large delay. For example, I hold the device move around, the track image and odometry needs 5~10 second to respond. Do you know why?

**Comment by arjunskumar** [comment]
@shmm91 I had the similar problem with Myteye and Intel D435

**Comment by shmm91** [comment]
@arjunskumar Have you solve the problem?

**Comment by arjunskumar** [comment]
@shmm91 not yet, i have this delay issues with Tx2 and intel realsense D435

**Comment by arjunskumar** [comment]
@shmm91 try reduce the feature count and turn off flow back. I got it working on my pc but not in TX2

**Comment by Lip0** [comment]
> @shmm91 not yet, i have this delay issues with Tx2 and intel realsense D435

**Comment by pamzerbhu** [comment]
Hi, the same device MYNTEYED and tx2 that I have met the same question also try to use VINS-Fusion-GPU but the problem remains.

**Comment by 0Jiahao** [comment]
@arjunskumar Hi! Have you tried out the VINS-Fusion-GPU? I can only run it by reducing features (to 80) and disabling the flow_back. Is it same to yours?

**Comment by pamzerbhu** [comment]
> Hi, the same device MYNTEYED and tx2 that I have met the same question. I try to use VINS-Fusion-GPU but not help with the problem.

I have solved it by setting flow_back: 0 max_cnt: 70  and use VINS-Fusion-GPU.

**Comment by Lsmartworld** [comment]
Hello, the same device MYNTEYED and tx2 that I have met the anther question.During the process of using VINS-FUSION, I found that when running stereo + IMU, the drift is very powerful. But when running stereo, it is very stable. Would you like to ask if you have encountered such a problem? @pamzerbhu

**Comment by pamzerbhu** [comment]
> Hello, the same device MYNTEYED and tx2 that I have met the anther question.During the process of using VINS-FUSION, I found that when running stereo + IMU, the drift is very powerful. But when running stereo, it is very stable. Would you like to ask if you have encountered such a problem? @pamzerbhu

I am sorry hadn't use stereo mode,  I only tried to use mono+IMU. But I have two suggests for this problem.
 1. Check you Extrinsic Parameters between IMU and Cam.  The standard Extrinsic Parameters which you read from Cam by MYNT SDK.
2. The scale of IMU parameters read by MYNT SDK has been enlarged 100 times. Please check it.
 Pamzerbhu

**Comment by Lsmartworld** [comment]
> > Hello, the same device MYNTEYED and tx2 that I have met the anther question.During the process of using VINS-FUSION, I found that when running stereo + IMU, the drift is very powerful. But when running stereo, it is very stable. Would you like to ask if you have encountered such a problem? @pamzerbhu
> 
> I am sorry hadn't use stereo mode, I only tried to use mono+IMU. But I have two suggests for this problem.
> 
> 1. Check you Extrinsic Parameters between IMU and Cam.  The standard Extrinsic Parameters which you read from Cam by MYNT SDK.
> 2. The scale of IMU parameters read by MYNT SDK has been enlarged 100 times. Please check it.
>    Pamzerbhu

Thank you for your answer.I can't understand the second suggest. where can check the parameter?

**Comment by pamzerbhu** [comment]
> > > Hello, the same device MYNTEYED and tx2 that I have met the anther question.During the process of using VINS-FUSION, I found that when running stereo + IMU, the drift is very powerful. But when running stereo, it is very stable. Would you like to ask if you have encountered such a problem? @pamzerbhu
> > 
> > 
> > I am sorry hadn't use stereo mode, I only tried to use mono+IMU. But I have two suggests for this problem.
> > 
> > 1. Check you Extrinsic Parameters between IMU and Cam.  The standard Extrinsic Parameters which you read from Cam by MYNT SDK.
> > 2. The scale of IMU parameters read by MYNT SDK has been enlarged 100 times. Please check it.
> >    Pamzerbhu
> 
> Thank you for your answer.I can't understand the second suggest. where can check the parameter?
Let me see files called:
1. "MYNT-EYE-VINS-FUSION-Samples/config/mynteye/mynteye_stereo_imu_config.yaml" 
2.  Param file you read from Cam named "image_params.params" and "imu_params.params"

**Comment by Lsmartworld** [comment]
> > > > Hello, the same device MYNTEYED and tx2 that I have met the anther question.During the process of using VINS-FUSION, I found that when running stereo + IMU, the drift is very powerful. But when running stereo, it is very stable. Would you like to ask if you have encountered such a problem? @pamzerbhu
> > > 
> > > 
> > > I am sorry hadn't use stereo mode, I only tried to use mono+IMU. But I have two suggests for this problem.
> > > 
> > > 1. Check you Extrinsic Parameters between IMU and Cam.  The standard Extrinsic Parameters which you read from Cam by MYNT SDK.
> > > 2. The scale of IMU parameters read by MYNT SDK has been enlarged 100 times. Please check it.
> > >    Pamzerbhu
> > 
> > 
> > Thank you for your answer.I can't understand the second suggest. where can check the parameter?
> > Let me see files called:
> 
> 1. "MYNT-EYE-VINS-FUSION-Samples/config/mynteye/mynteye_stereo_imu_config.yaml"
> 2. Param file you read from Cam named "image_params.params" and "imu_params.params"

Thank you very much ! But I can't solve the problem.

**Comment by zxh2015** [comment]
Have you solve the problem?

**Comment by pamzerbhu** [comment]
I have solved it by setting flow_back: 0 max_cnt: 70 and use VINS-Fusion-GPU.

> Have you solve the problem?

I have solved it by setting flow_back: 0 max_cnt: 70 and use VINS-Fusion-GPU.

**Comment by zxh2015** [comment]
> I have solved it by setting flow_back: 0 max_cnt: 70 and use VINS-Fusion-GPU.
> 
> > Have you solve the problem?
> 
> I have solved it by setting flow_back: 0 max_cnt: 70 and use VINS-Fusion-GPU.

oh, no, I don't have GPU with my computer....but I will try it. Thanks!

**Comment by zxh2015** [comment]
I have solved it by starting the SDK with another launch file
`
roslaunch mynteye_wrapper_d vi_fusion.launch streams_mode:=1
`
now, the image size is 1280*480
I don't know  if the size is the cause .
it works

**Comment by robin-shaun** [comment]
Reducing the frame rate works.
