### ISSUE TITLE
Tracking is very slow in Jetson TX2

### ISSUE THREAD

**Issue by arjunskumar** [HKUST-Aerial-Robotics/VINS-Fusion#21]
Tracking is very slow in Jetson TX2, I reduced number of features but still tracking is very slow more than 10 seconds.

**Comment by pjrambo** [comment]
I have written an gpu acceleration version VINS-Fusion, you can go to this repo for help.
https://github.com/pjrambo/VINS-Fusion-gpu
It can run in real-time with 250 feature points.

**Comment by arjunskumar** [comment]
@pjrambo Thanks
