### ISSUE TITLE
D435i wrong in rviz

### ISSUE THREAD

**Issue by cwahaha51** [HKUST-Aerial-Robotics/VINS-Fusion#228]
![问题](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/assets/110490547/8a120c7b-864b-49ba-bf60-4dd242c5c1cf)

**Comment by cwahaha51** [comment]
roslaunch vins vins_rviz.launch 


[ERROR] [1704862146.656131470]: Ignoring transform for child_frame_id "body" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (-nan -nan -nan -nan)
[ERROR] [1704862146.656158407]: Ignoring transform for child_frame_id "body" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)

**Comment by srendit** [comment]
I meet the same problem. What do you do to slove the problem.

**Comment by Duyj-04** [comment]
I meet the same problem. What do you do to slove the problem ?
