### ISSUE TITLE
Could this code run using  Monocualr camera + IMU + GPS on ROS environment

### ISSUE THREAD

**Issue by ctwu0314** [HKUST-Aerial-Robotics/VINS-Fusion#23]
Thank you for your great work.
Could this code run using  Monocualr camera + IMU + GPS on ROS environment?
Or how to modify ?
thank you very much.

Nelosn Wu

**Comment by shaozu** [comment]
Hi, Nelosn Wu. You may need to remap your GPS topic to `/gps`, also  please refer [this file](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/master/global_fusion/src/globalOptNode.cpp)   in case you want to modify.

**Comment by animeshsahu80** [comment]
did it work? @ctwu0314

**Comment by ssssjiang** [comment]
> 嗨，Nelosn Wu。您可能需要重新映射您的GPS主题`/gps`， 如果您想要修改，请参阅[此文件](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/master/global_fusion/src/globalOptNode.cpp)。
感谢你的指导，但是方便更具体一点么？
