### ISSUE TITLE
when i try the EuRoC Example,opencv error

### ISSUE THREAD

**Issue by zhendebufapyq** [HKUST-Aerial-Robotics/VINS-Fusion#232]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) /home/ubuntu/build_opencv/opencv/modules/core/src/matrix.cpp:250: error: (-215:Assertion failed) s &gt;= 0 in function 'setSize'

Aborted (core dumped)
![IMG_20240302_140433](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/assets/147624475/b1e5d772-8a83-4a12-af53-918f5f61891d)

**Comment by SanghyunPark01** [comment]
Try this and build again  
`find_package(OpenCV REQUIRED)` => `find_package(OpenCV3 REQUIRED)`

**Comment by zhendebufapyq** [comment]
thanks，everything is all right.

> Try this and build again `find_package(OpenCV REQUIRED)` => `find_package(OpenCV3 REQUIRED)`
