### ISSUE TITLE
get cam0_calib file

### ISSUE THREAD

**Issue by zz1120122573** [HKUST-Aerial-Robotics/VINS-Fusion#26]
Hi, if I use another stereo camera, how can I transform
cam0_pinhole.yaml to  cam0_mei.yaml?  

Thanks!

**Comment by shaozu** [comment]
Hi, pinhole itself is ok, and there is no need to transform one to the other.

**Comment by volcanoh** [comment]
> Hi, pinhole itself is ok, and there is no need to transform one to the other.

I have a question, why pinhole is worse than mei or equi is euroc MH01 , but pinhole is ok in vins mono?

**Comment by zhouhaoran-TJU** [comment]
> > Hi, pinhole itself is ok, and there is no need to transform one to the other.
> 
> I have a question, why pinhole is worse than mei or equi is euroc MH01 , but pinhole is ok in vins mono?

Hi, I have the same question, It's really puzzling that when I using pinhole.yaml, it performed worse, although the camera type is pinhole in the dataset.
