### ISSUE TITLE
Can VINS run in simulation environment?

### ISSUE THREAD

**Issue by ElderWanng** [HKUST-Aerial-Robotics/VINS-Fusion#32]
For example, I want to run this project in `Gazebo`? How can I configure some parameters?

**Comment by crankler** [comment]
Have you solve this problem? I also just waht to simulation this , and I can see someone use VINS-Mono on gazebo in YouTube.

Thank you for your apply!

**Comment by rreddy78** [comment]
Better to use CARLA for this. I have tried VINS-Mono and VINS -Fusion with CARLA. VINS-Mono works well, but VINS-Fusion does not. Not sure why
