### ISSUE TITLE
Intrinsic and extrinsic calibration 

### ISSUE THREAD

**Issue by SainaRez** [HKUST-Aerial-Robotics/VINS-Fusion#55]
How did you get the extrinsic calibration parameters for realsense D435i and imu and the imu intrinsic parameters? Did you use a specific package?

**Comment by HKVINS89757** [comment]
kalibr

**Comment by zgxsin** [comment]
Hi @HKVINS89757 , can i get the extrinsic transformation between camera and IMU for realsense D435i from the tf tree by launching `realsense2_camera` package?

Here is what i did:

1.  Echo image topic and check its frame_id
![image](https://user-images.githubusercontent.com/23395893/68303031-5beab880-00a3-11ea-885d-aa7e28c4950c.png)

1. Echo imu topic and check its frame_id
![image](https://user-images.githubusercontent.com/23395893/68303164-948a9200-00a3-11ea-840c-536acee0851f.png)

1. Use tf_echo to get the transformation between from image to  imu.
![image](https://user-images.githubusercontent.com/23395893/68303266-ca2f7b00-00a3-11ea-997c-9f1810cb7d26.png)

I compare this result to [here](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/master/config/realsense_d435i/realsense_stereo_imu_config.yaml). They are not consistent at all. Any idea?

**Comment by shirbarzel** [comment]
Hi @zgxsin I saw you mentioned another issue but still I don't understand how to update my realsense_stereo_imu_config.yaml according to my camera?
Can you please elaborate?
