### ISSUE TITLE
How to improve the tracking frequency?

### ISSUE THREAD

**Issue by MoonUniverse** [HKUST-Aerial-Robotics/VINS-Fusion#63]
Hi everyone! 
Thank you for your working!I am currently using this code for my drone. I have a problem with the tracking frequency.
~~~
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
~~~
The frequence of publish tracking result seems to be only up to the image frequency.But In my controller need a higher odometry feedback frequency(for examp 100hz 200hz).So can I achieve high tracking frequency by modifying the code?

Thanks!

**Comment by djramakrishna** [comment]
Hi @MoonUniverse, I'd like to know how did you increase your odometry frequency? I'm looking for something similar as I wanted to publish the odometry topics at a much higher frequency than the default 10 Hz. Looking forward to your comments on this aspect. Thank you.
