### ISSUE TITLE
launch problem

### ISSUE THREAD

**Issue by caoyifeng001** [HKUST-Aerial-Robotics/VINS-Fusion#80]
我把这几个node 放在一个launch
`<launch>
    <node name="rvizvisualisation" pkg="rviz" type="rviz" output="log" args="-d $(find vins)/../config/vins_rviz_config.rviz" />
    <node name="vins_node" pkg="vins" type="vins_node" output="screen" args="/home/cbin/vinsfusin_ws/src/VINS-Fusion/config/euroc/euroc_stereo_imu_config.yaml" /> 
    <node name="loop_fusion_node" pkg="loop_fusion" type="loop_fusion_node" output="screen" args="/home/cbin/vinsfusin_ws/src/VINS-Fusion/config/euroc/euroc_stereo_imu_config.yaml" />
   <node name="playe" pkg="rosbag" type="play" output="screen" args=" /home/cbin/data_set/SLAM/MH_01_easy.bag"/>
</launch>
`
其他都正常rviz上没有反应。

**Comment by awenbigprawn** [comment]
how did you fix that? I have the same question
