### ISSUE TITLE
Assertion `px != 0' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by tekrajchhetri** [HKUST-Aerial-Robotics/VINS-Fusion#89]
I am getting core dump issue even with the provided default configuration and also with my own. I ran MH_01 euroc dataset with imu. I also followed the suggestions from issue  #36 for the fix i.e. installing stable version of ceras and eigen.

![Screenshot from 2019-11-20 19-37-47](https://user-images.githubusercontent.com/52251022/69263824-bff69c00-0bce-11ea-9928-2f96d62490fc.png)

Thank you.

**Comment by jerrykingnice** [comment]
Hi
you need to notice,the cmd you type.
Instead of  type rosrun  vins vins_node euroc_mono_imu_config.yaml ,
you should give rosrun  vins vins_node **catkin_ws/src/VINS-Fusion/config/locate/euroc_mono_imu_config.yaml**

**Comment by tekrajchhetri** [comment]
@jerrykingnice thanks for your response.  I was in the directory where the launch files are present so I just gave the file name. Anyway when i run following what you said, I got the following.

![imu--Screenshot from 2019-11-25 12-02-33](https://user-images.githubusercontent.com/52251022/69530868-82ea2b00-0f7b-11ea-8b6b-aa5835a9df40.png)

**Comment by tekrajchhetri** [comment]
but now I am getting a gyroscope bias error. The calibration was performed using kalibr.

**Comment by haithink** [comment]
I also encounttered this problem. But in some cases, there was not this problem And the only difference is the version of some thirdparty libraries such as boost or opencv.

**Comment by tekrajchhetri** [comment]
@haithink Could you provide information on the version of the libraries you used? This is a little strange. Isn't it that as long as the method that it is currently using is available then it should work otherwise will everyone will be stick to use the same version?

**Comment by haithink** [comment]
@tekrajchhetri  When I use boost1.71 , then no problem;  In boost 1.54 case, then assert failed. I have googled this problem, many people said that it occured because of using shared pointers without initialization.[https://stackoverflow.com/questions/3541179/shared-ptr-assertion-px-0-failed](refer this)

**Comment by LouisValery** [comment]
I had this error. In my case it mas clearly  a problem linked to the parameters.
In particular the two camera files where not correctly set (in the euroc_mono_imu_config.yaml):
cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"

make sur that the names of these files are correct and that thes files are in the good folder.

**Comment by tekrajchhetri** [comment]
closing this issue as i am no longer working with it.

**Comment by trunc8** [comment]
> @jerrykingnice thanks for your response. I was in the directory where the launch files are present so I just gave the file name.

For the benefit of anyone else that stumbles on this issue, giving just the file name _will_ create this error. From the code in `parameters.cpp`:
```cpp
    int pn = config_file.find_last_of('/');
    std::string configPath = config_file.substr(0, pn);
```
So you require at least one directory name in your terminal argument. If you input just the filename, `pn=-1` and `configPath` will take the entire `config_file` string. This gives nonsensical file paths later, as is evident in the image of the first post in this thread-
`reading parameter of camera euroc_stereo_imu_config.yaml/cam0_mei.yaml`
