### ISSUE TITLE
How to modify the program to make the frequency of publish tracking result as fast as the image?

### ISSUE THREAD

**Issue by ctwu0314** [HKUST-Aerial-Robotics/VINS-Fusion#97]
The freq parameter doesn't seem to work.
(ex. In euroc_mono_imu_config.yaml
freq: 10 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image)
I find that it doesn't read the freq parameter in parameters.cpp .
How to modify the program to make the frequency of publish tracking result as fast as the image?

**Comment by shaozu** [comment]
Please refer to issue #92.
